version: '3.1'

version: '3'


services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    container_name: mongodb
    networks:
      - spring-boot-mongodb-network
  reading-is-good:
    image: barisaslan/reading-is-good
    container_name: reading-is-good
    restart: always
    networks:
      - spring-boot-mongodb-network
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAR_FILE=build/libs/reading-is-good.jar
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_URI=mongodb://localhost:27017/mongodb

networks:
  spring-boot-mongodb-network:
    driver: bridge

